Repository tier4/ota-client, pull requests merged in 2025-08, with the labels that each got.

#608 feat!: use HTTP host for gRPC endpoint
  src/otaclient/_logging.py
  tests/test_otaclient/test_logging.py
Labels: feature, breaking_change, need_backport: v3.10

#614 refactor!: otaproxy: for multiple ECUs environment, disable OTA cache for child ECUs
  src/otaclient/_otaproxy_ctx.py
Labels: refactor, need_backport: v3.10

#613 fix: otaproxy cannot commit cache to db when the cache entry already exists
  src/ota_proxy/cache_streaming.py
  src/ota_proxy/ota_cache.py
  tests/test_ota_proxy/test_cache_streaming.py
Labels: bug, need_backport: v3.10

#616 [3.10] fix: publish metrics after exceptions handling (#609)
  src/otaclient/metrics.py
  src/otaclient/ota_core.py
  tests/test_otaclient/test_ota_core.py
Labels: backport

#619 [3.10] fix: update_slot doesn't raise exception on process_regular_files failed(#612)
  src/otaclient/create_standby/update_slot.py
  tests/test_otaclient/test_create_standby/test_update_slot_e2e.py
Labels: backport

#620 [3.10] feat: add cdn cache hit ratio into metrics (#610)
  src/ota_proxy/ota_cache.py
  src/otaclient/metrics.py
  tests/test_ota_proxy/test_ota_cache.py
  tests/test_otaclient/test_metrics.py
Labels: backport

#621 [3.10] refactor!: otaproxy: for multiple ECUs environment, disable OTA cache…
  src/otaclient/_otaproxy_ctx.py
Labels: backport

#624 refinement: set status as SUCCESS instead of restarting in ClientUpdate
  .github/actions/generate_manifest/generate_manifest.py
  src/otaclient/errors.py
  src/otaclient/ota_core.py
  tests/test_otaclient/test_ota_core.py
Labels: refinement, need_backport: v3.10

#625 [3.10] refinement: set status as SUCCESS instead of restarting in ClientUpdate
  .github/actions/generate_manifest/generate_manifest.py
  src/otaclient/errors.py
  src/otaclient/ota_core.py
  tests/test_otaclient/test_ota_core.py
Labels: refinement, backport

#626 feat!: migrate to json logging
  src/otaclient/configs/_cfg_configurable.py
  tests/test_otaclient/test_logging.py
Labels: feature, breaking_change

#627 chore: add system uptime debug message
  src/otaclient/main.py
Labels: chore

#639 fix!: remove rollback API support
  src/otaclient/grpc/api_v2/servicer.py
  src/otaclient/ota_core.py
  tests/test_otaclient/test_grpc/test_api_v2/test_servicer.py
Labels: breaking_change, security

#644 feat: add request id as common ID shared between multiple ECUs
  proto/otaclient_v2.proto
  src/otaclient/_types.py
  src/otaclient/_utils.py
  src/otaclient/grpc/api_v2/servicer.py
  src/otaclient/metrics.py
  src/otaclient/ota_core.py
  src/otaclient_api/v2/_types.py
  src/otaclient_api/v2/otaclient_v2_pb2.py
  tests/test_otaclient/test_grpc/test_api_v2/test_servicer.py
  tests/test_otaclient/test_ota_core.py
Labels: feature, proto_change

#640 feat: make next OTA delta calculation faster by preserving OTA resources dir after OTA
  src/otaclient/configs/_cfg_consts.py
  src/otaclient/create_standby/delta_gen.py
  src/otaclient/create_standby/update_slot.py
  src/otaclient/ota_core.py
  tests/test_otaclient/test_create_standby/conftest.py
  tests/test_otaclient/test_ota_core.py
Labels: feature

#642 feat: do fstrim during OTA(inplace mode) and on otaclient starts up
  src/otaclient/configs/_cfg_configurable.py
  src/otaclient/ota_core.py
  src/otaclient_common/linux.py
  tests/test_otaclient/test_ota_core.py
Labels: feature

#638 refactor: ota_core: decoupling actual OTA meta downloading implementations away from ota_core
  src/otaclient/_download_resources.py
  src/otaclient/client_package.py
  src/otaclient/errors.py
  src/otaclient/ota_core.py
  tests/test_otaclient/test_client_package.py
  tests/test_otaclient/test_ota_core.py
Labels: refactor

#645 refactor!: make ota_core as a package for better code managing; remove rollback impl
  src/otaclient/grpc/README.md
  src/otaclient/ota_core.py
  src/otaclient/ota_core/README.md
  src/otaclient/ota_core/__init__.py
  src/otaclient/ota_core/_client_updater.py
  src/otaclient/ota_core/_common.py
  src/otaclient/ota_core/_download_resources.py
  src/otaclient/ota_core/_main.py
  src/otaclient/ota_core/_updater.py
  src/otaclient/ota_core/_updater_base.py
  tests/conftest.py
  tests/test_otaclient/test_ota_core.py
Labels: refactor, breaking_change

#646 refine: resume OTA: only scan needed resources; inplace mode: try to reuse standby slot base file_table for OTA retry
  src/otaclient/configs/_cfg_consts.py
  src/otaclient/create_standby/delta_gen.py
  src/otaclient/create_standby/resume_ota.py
  src/otaclient/create_standby/update_slot.py
  src/otaclient/ota_core/_updater.py
  src/otaclient_common/__init__.py
  tests/test_otaclient/test_ota_core.py
Labels: refinement

#649 feat: enhanced inplace mode and rebuild mode: fastpath by using OTA resources dir
  src/otaclient/create_standby/_common.py
  src/otaclient/create_standby/resume_ota.py
  src/otaclient/create_standby/update_slot.py
  src/otaclient/ota_core/_main.py
  src/otaclient/ota_core/_updater.py
  src/otaclient_common/thread_safe_container.py
Labels: feature

#654 refinement: mount standby slot with noatime
  src/otaclient_common/cmdhelper.py
Labels: refinement

#657 refine: create_standby: IO tuning, optimize mount options
  src/otaclient_common/cmdhelper.py
Labels: refinement

#651 refinement: reduce the number of stat calling
  src/otaclient/create_standby/delta_gen.py
  src/otaclient_common/_io.py
  src/otaclient_common/common.py
  src/otaclient_common/linux.py
  src/otaclient_common/persist_file_handling.py
Labels: refinement

#655 ci: use native arm runner for squashfs release
  .github/workflows/release.yml
Labels: build/ci
