Repository tier4/ota-client, pull requests merged in 2025-09, with the labels that each got.

#656 fix: fix dynamic client exit after metrics publish
  src/otaclient/ota_core/_main.py
  tests/test_otaclient/test_ota_core.py
Labels: bug

#666 chore: cleanup ota_metadata.legacy, fix up test_otaproxy accordingly
  src/ota_metadata/legacy/__init__.py
  src/ota_metadata/legacy/_parser.py
  src/ota_metadata/legacy/_types.py
  src/ota_metadata/legacy/ota_metafiles_pb2.py
  src/ota_metadata/legacy/ota_metafiles_pb2.pyi
  tests/test_ota_metadata/test_legacy/__init__.py
  tests/test_ota_metadata/test_legacy/test_legacy.py
  tests/test_ota_proxy/test_ota_proxy_e2e.py
  tools/offline_ota_image_builder/README.md
  tools/offline_ota_image_builder/__init__.py
  tools/offline_ota_image_builder/__main__.py
  tools/offline_ota_image_builder/builder.py
  tools/offline_ota_image_builder/configs.py
  tools/offline_ota_image_builder/manifest.py
  tools/offline_ota_image_builder/utils.py
Labels: chore

#677 test: update otaproxy e2e test files
  pyproject.toml
  tests/test_ota_proxy/test_ota_proxy_e2e.py
Labels: test_files
