Repository tier4/ota-client, pull requests merged in 2025-07, with the labels that each got.

#586 [3.9] ci: introduce deps locked wheel package build for otaclient with hatch build hook and uv; cherry-pick #580
  .github/workflows/release.yml
  .github/workflows/update_lockfile.yaml
  docker/test_base/entry_point.sh
  pyproject.toml
  requirements.lock
  scripts/hatch_build_lock_deps.py
Labels: build/ci

#587 ci: introduce deps locked wheel package build for otaclient with hatch build hook and uv
  .github/workflows/release.yml
  .github/workflows/update_lockfile.yaml
  docker/test_base/entry_point.sh
  pyproject.toml
  scripts/hatch_build_lock_deps.py
Labels: build/ci

#590 [3.9] feat: introduce OTA resume on inplace update mode
  src/otaclient/create_standby/delta_gen.py
  src/otaclient/create_standby/resume_ota.py
  src/otaclient/ota_core.py
  src/otaclient_common/_io.py
  tests/test_otaclient/test_create_standby/conftest.py
  tests/test_otaclient/test_create_standby/test_resume_ota.py
  tests/test_otaclient_common/test_io.py
Labels: feature, need_forward_port

#592 [3.9] fix: replace_root and TopDownCommonShortestPath: DO NOT resolve input paths
  src/otaclient/create_standby/utils.py
  src/otaclient_common/__init__.py
Labels: bug, need_forward_port

#602 refinement: skip metafiles parsing for client update
  src/ota_metadata/legacy2/metadata.py
  src/otaclient/client_package.py
  src/otaclient/ota_core.py
  tests/test_ota_metadata/test_legacy2/test_metadata.py
Labels: refinement

#603 chore: add in place mode metrics
  src/otaclient/metrics.py
  src/otaclient/ota_core.py
Labels: chore

#609 fix: publish metrics after exceptions handling
  src/otaclient/metrics.py
  src/otaclient/ota_core.py
  tests/test_otaclient/test_ota_core.py
Labels: bug
