Repository tier4/ota-client, pull requests merged in 2025-06, with the labels that each got.

#543 refactor: remove unnecessary status modules
  src/otaclient/configs/_cfg_consts.py
  src/otaclient/grpc/api_v2/ecu_status.py
  tests/test_otaclient/test_grpc/test_api_v2/test_ecu_status.py
Labels: refactor

#550 deps: update requests package to 2.32.4
  pyproject.toml
  requirements.txt
  uv.lock
Labels: dependencies

#552 test: fix flaky logging test
  tests/test_otaclient/test_logging.py
Labels: test_files

#557 fix: ensure status is pushed for every push interval, ensure firmware_version is pushed on otaclient starts up
  src/otaclient/_status_monitor.py
  src/otaclient/ota_core.py
Labels: bug, need_backport

#563 fix: fix mount option in bind with R/W for dynamic client
  src/otaclient/client_package.py
  src/otaclient_common/cmdhelper.py
  tests/test_otaclient_common/test_cmdhelper.py
Labels: bug

#564 fix: ensure standby device umounted before choort for dynamic client
  src/otaclient/boot_control/_grub.py
  src/otaclient/boot_control/_jetson_cboot.py
  src/otaclient/boot_control/_jetson_uefi.py
  src/otaclient/boot_control/_rpi_boot.py
  src/otaclient/boot_control/protocol.py
  src/otaclient/client_package.py
  src/otaclient/main.py
  tests/test_otaclient/test_client_package.py
Labels: bug

#568 fix: always report SUCCESS after ClientUpdate
  src/otaclient/boot_control/_ota_status_control.py
  tests/test_otaclient/test_boot_control/test_ota_status_control.py
Labels: bug

#571 refactor: downloader: use posix_fadvise syscall to indicate kernel dropping file caches after write
  src/otaclient_common/downloader.py
Labels: refactor, need_backport

#574 [backport v3.9] chore: support pre-release identification in squashfs filename
  .github/actions/generate_manifest/generate_manifest.py
  .github/workflows/release.yml
Labels: build/ci, backport

#573 chore: support pre-release identification in squashfs filename
  .github/actions/generate_manifest/generate_manifest.py
  .github/workflows/release.yml
Labels: build/ci

#539 [3.9][RT4-17099][feat-dev-part1] feat(ota-metadata): refine the file_table definition, introduce helper utils
  pyproject.toml
  src/ota_metadata/file_table/__init__.py
  src/ota_metadata/file_table/_orm.py
  src/ota_metadata/file_table/_table.py
  src/ota_metadata/file_table/_types.py
  src/ota_metadata/file_table/db.py
  src/ota_metadata/file_table/utils.py
  src/ota_metadata/legacy2/csv_parser.py
  src/ota_metadata/legacy2/metadata.py
  src/ota_metadata/legacy2/rs_table.py
  src/otaclient/boot_control/_jetson_uefi.py
  src/otaclient/ota_core.py
  uv.lock
Labels: feature

#540 [3.9][RT4-17099][feat-dev-part2] feat(otaclient.create_standby): re-implement the create_standby functionality, introduce in-place update mode and refine rebuild mode
  src/ota_metadata/file_table/utils.py
  src/otaclient/configs/_cfg_configurable.py
  src/otaclient/create_standby/__init__.py
  src/otaclient/create_standby/_delta_gen.py
  src/otaclient/create_standby/delta_gen.py
  src/otaclient/create_standby/rebuild_mode.py
  src/otaclient/create_standby/update_slot.py
  src/otaclient/create_standby/utils.py
  src/otaclient_common/cmdhelper.py
  src/otaclient_common/common.py
  src/otaclient_common/linux.py
Labels: feature

#541 [3.9][RT4-17099][feat-dev-part3] feat: integrate the new create_standby implementation into otaclient
  src/ota_metadata/file_table/db.py
  src/ota_metadata/file_table/utils.py
  src/ota_proxy/db.py
  src/otaclient/boot_control/_grub.py
  src/otaclient/boot_control/_jetson_cboot.py
  src/otaclient/boot_control/_jetson_common.py
  src/otaclient/boot_control/_jetson_uefi.py
  src/otaclient/boot_control/_ota_status_control.py
  src/otaclient/boot_control/_rpi_boot.py
  src/otaclient/boot_control/_slot_mnt_helper.py
  src/otaclient/boot_control/protocol.py
  src/otaclient/ota_core.py
Labels: feature

#579 [3.9][RT4-17099] tests: test files for new create_standby implementation
  .github/workflows/test.yaml
  src/otaclient/create_standby/utils.py
  tests/conftest.py
  tests/test_ota_metadata/test_file_table/test__orm.py
  tests/test_ota_metadata/test_file_table/test__table.py
  tests/test_ota_metadata/test_file_table/test__types.py
  tests/test_ota_metadata/test_file_table/test_utils.py
  tests/test_ota_metadata/test_legacy2/test_csv_parser.py
  tests/test_otaclient/test_boot_control/test_grub.py
  tests/test_otaclient/test_boot_control/test_ota_status_control.py
  tests/test_otaclient/test_boot_control/test_rpi_boot.py
  tests/test_otaclient/test_create_standby.py
  tests/test_otaclient/test_create_standby/__init__.py
  tests/test_otaclient/test_create_standby/conftest.py
  tests/test_otaclient/test_create_standby/test_delta_gen_e2e.py
  tests/test_otaclient/test_create_standby/test_update_slot_e2e.py
  tests/test_otaclient/test_ota_core.py
  tests/utils.py
Labels: test_files

#581 [3.9][RT4-17099] feat: new create_standby implementation with full inplace update mode support
  .github/workflows/test.yaml
  pyproject.toml
  src/ota_metadata/file_table/__init__.py
  src/ota_metadata/file_table/_orm.py
  src/ota_metadata/file_table/_table.py
  src/ota_metadata/file_table/_types.py
  src/ota_metadata/file_table/db.py
  src/ota_metadata/file_table/utils.py
  src/ota_metadata/legacy2/csv_parser.py
  src/ota_metadata/legacy2/metadata.py
  src/ota_metadata/legacy2/rs_table.py
  src/ota_proxy/db.py
  src/otaclient/boot_control/_grub.py
  src/otaclient/boot_control/_jetson_cboot.py
  src/otaclient/boot_control/_jetson_common.py
  src/otaclient/boot_control/_jetson_uefi.py
  src/otaclient/boot_control/_ota_status_control.py
  src/otaclient/boot_control/_rpi_boot.py
  src/otaclient/boot_control/_slot_mnt_helper.py
  src/otaclient/boot_control/protocol.py
  src/otaclient/configs/_cfg_configurable.py
  src/otaclient/create_standby/__init__.py
  src/otaclient/create_standby/_delta_gen.py
  src/otaclient/create_standby/delta_gen.py
  src/otaclient/create_standby/rebuild_mode.py
  src/otaclient/create_standby/update_slot.py
  src/otaclient/create_standby/utils.py
  src/otaclient/ota_core.py
  src/otaclient_common/cmdhelper.py
  src/otaclient_common/common.py
  src/otaclient_common/linux.py
  tests/conftest.py
  tests/test_ota_metadata/test_file_table/test__orm.py
  tests/test_ota_metadata/test_file_table/test__table.py
  tests/test_ota_metadata/test_file_table/test__types.py
  tests/test_ota_metadata/test_file_table/test_utils.py
  tests/test_ota_metadata/test_legacy2/test_csv_parser.py
  tests/test_otaclient/test_boot_control/test_grub.py
  tests/test_otaclient/test_boot_control/test_ota_status_control.py
  tests/test_otaclient/test_boot_control/test_rpi_boot.py
  tests/test_otaclient/test_create_standby.py
  tests/test_otaclient/test_create_standby/__init__.py
  tests/test_otaclient/test_create_standby/conftest.py
  tests/test_otaclient/test_create_standby/test_delta_gen_e2e.py
  tests/test_otaclient/test_create_standby/test_update_slot_e2e.py
  tests/test_otaclient/test_ota_core.py
  tests/utils.py
  uv.lock
Labels: feature

#582 [3.9] feat: mount tmpfs as OTA update session workdir
  src/otaclient/_utils.py
  src/otaclient/configs/_cfg_configurable.py
  src/otaclient/configs/_cfg_consts.py
  src/otaclient/main.py
  src/otaclient/ota_core.py
  src/otaclient_common/cmdhelper.py
  tests/conftest.py
Labels: feature, need_forward_port

#583 chore: release v3.9.0
  src/otaclient/ota_core.py
Labels: chore, tag
