Repository tier4/ota-client, pull requests merged in 2025-03, with the labels that each got.

#497 docs: update test manual
  DEVELOPMENT.md
Labels: documentation

#498 fix(v3.8.x): rpi_boot.update_firmware: ensure `/tmp` folder exists when doing flash-kernel
  src/otaclient/boot_control/_rpi_boot.py
Labels: bug

#499 fix: rpi_boot.update_firmware: ensure /tmp folder exists when doing flash-kernel
  src/otaclient/boot_control/_rpi_boot.py
Labels: bug

#501 fix(otaclient v3.8.x): Add timeout when downloading "metadata.jwt" and *.pem files
  src/ota_metadata/legacy/parser.py
Labels: refactor, don't merge

#504 feat: retry_task_map: supports exits on exceeding max_retry_on_entry
  src/otaclient_common/retry_task_map.py
  tests/test_otaclient_common/test_retry_task_map.py
Labels: feature

#503 fix: otaproxy_ctx: fix otaproxy life-cycle management thread exits at OTA failed
  src/otaclient/_otaproxy_ctx.py
Labels: bug

#507 tests: refine tests for retry_task_map
  tests/test_otaclient_common/test_retry_task_map.py
Labels: test_files

#505 refactor: move client manifest schema into /src directory
  .github/actions/generate_manifest/action.yml
  .github/actions/generate_manifest/generate_manifest.py
  pyproject.toml
  src/otaclient_manifest/init.py
  src/otaclient_manifest/schema.py
  tools/local_ota/README.md
Labels: refactor

#509 refactor: encapsulate data of ecu status
  src/otaclient/grpc/api_v2/ecu_status.py
  tests/test_otaclient/test_grpc/test_api_v2/test_ecu_status.py
Labels: refactor

#506 feat: extend clientupdate command
  proto/otaclient_v2.proto
  src/otaclient_api/v2/_types.py
  src/otaclient_api/v2/otaclient_v2_pb2.py
  src/otaclient_api/v2/otaclient_v2_pb2.pyi
  src/otaclient_api/v2/otaclient_v2_pb2_grpc.py
Labels: proto_change

#513 fix: rename wrong initialization file name
  src/otaclient_manifest/__init__.py
Labels: build/ci

#510 refactor: aggregate duplicated code in servicer
  src/otaclient/grpc/api_v2/servicer.py
  tests/test_otaclient/test_grpc/test_api_v2/test_servicer.py
Labels: refactor
