Repository tier4/ota-client, pull requests merged in 2025-02, with the labels that each got.

#478 ci: add squashfs build jobs
  .github/actions/build_patches/action.yml
  .github/actions/build_squashfs_image/action.yml
  .github/actions/generate_manifest/action.yml
  .github/actions/generate_manifest/generate_manifest.py
  .github/actions/generate_manifest/schema.py
  .github/workflows/release.yml
  .github/workflows/test.yaml
  DEVELOPMENT.md
  docker/app_img/Dockerfile
  docker/app_img/README.md
  docker/test_base/docker-compose_tests.yml
Labels: build/ci

#482 feat: integrate new ota_metadata implementation for legacy OTA image
  src/ota_metadata/legacy2/metadata.py
  src/otaclient/create_standby/__init__.py
  src/otaclient/create_standby/_delta_gen.py
  src/otaclient/create_standby/common.py
  src/otaclient/create_standby/interface.py
  src/otaclient/create_standby/rebuild_mode.py
  src/otaclient/ota_core.py
  src/otaclient_common/__init__.py
  src/otaclient_common/downloader.py
  src/otaclient_common/retry_task_map.py
  tests/test_otaclient/test_create_standby.py
  tests/test_otaclient/test_ota_core.py
Labels: feature

#488 feat: status_monitor: log otaclient status every 60s when active OTA ongoing
  src/otaclient/_status_monitor.py
  src/otaclient/ota_core.py
Labels: feature

#487 feat: create_standby.rebuild_mode: file_table at delta_src assisted delta_calculation
  pyproject.toml
  requirements.txt
  src/ota_metadata/file_table/_orm.py
  src/ota_metadata/file_table/_table.py
  src/ota_metadata/legacy2/metadata.py
  src/ota_metadata/legacy2/rs_table.py
  src/otaclient/create_standby/_delta_gen.py
  src/otaclient/ota_core.py
  src/otaclient_common/__init__.py
  src/otaclient_common/_io.py
  src/otaclient_common/downloader.py
  tests/conftest.py
  tests/test_otaclient/test_boot_control/test_grub.py
  tests/test_otaclient/test_create_standby.py
Labels: feature

#492 fix: delta_gen: fix semaphore not being reclaimed in full disk scan mode
  docker/test_base/Dockerfile
  src/otaclient/create_standby/_delta_gen.py
Labels: bug
